version: '3'
services: 
    meshastrapi:
        image: strapi/strapi
        restart: unless-stopped
        container_name: meshabackend
        volumes:
        - ./meshabackup/:/srv/app
        ports:
            - '5002:1337'
